### ISSUE TITLE
Full screen button not working

### ISSUE THREAD

**Issue by aliya-ryan** [digidem/alianza-ceibo-maps#13]
The full screen button seems to be working in this version of the map: 

http://lab.digital-democracy.org/alianza-ceibo-maps/#8.3/0.006/-76.7122

but does not seem to work when embedded in the Alianza Ceibo test website:

https://www.alianzaceibo.org/programas/

**Comment by okdistribute** [comment]
Hey @aliya-ryan. That embed iframe needs to have the `allowfullscreen` attribute, like this:

```
<iframe src="https://lab.digital-democracy.org/alianza-ceibo-maps/" width="100%" height="300" allowfullscreen></iframe>
```
