### ISSUE TITLE
misplleing in areas.json 

### ISSUE THREAD

**Issue by okdistribute** [digidem/alianza-ceibo-maps#24]
Seems like one of the areas is spelled differently in the airtable vs. areas.json...
```
-        "name": "Sinangoe"
+        "name": "Sinangue"
```
where is areas.json coming from? Can we simply change it in the git? Which one is the right name?

**Comment by aliya-ryan** [comment]
The right name is **Sinangoe** - I can't find the areas.json - Greg put them altogether from files I sent him and it doesn't seem to be stored in our shared folder. If it can't be changed don't worry - it is a minimal problem and we can change it in a week when Greg reappears.

**Comment by okdistribute** [comment]
OK it seems to be spelled 'Sinangue' in the airtable export, which is causing problems when trying to do zoom when clicking on the sidebar

**Comment by okdistribute** [comment]
@aliya-ryan on it
