### ISSUE TITLE
Only make sidebar functional for **communities with stories**

### ISSUE THREAD

**Issue by aliya-ryan** [digidem/alianza-ceibo-maps#26]
When the sidebar feature is implemented, our partners have asked that initially only the communities that are the special ones with blogs etc. be made clickable, and appear in the sidebar. 

This is because they have not finished adding the descriptions and photos for all the communities and want it to be consistent. 

They'll add the other descriptions in time to the air table and when they are ready they will let us know in order to change this.

**Comment by aliya-ryan** [comment]
I hope this is reasonably easy to manage. If it adds a lot of complication / work let me know.

**Comment by okdistribute** [comment]
This is implemented now but the total for installations (water and solar) are still based on all communities, even those without stories.
