### ISSUE TITLE
Clicking a community dot 

### ISSUE THREAD

**Issue by okdistribute** [digidem/alianza-ceibo-maps#32]
Should open up the sidebar for that community only if that community has a story.

**Comment by aliya-ryan** [comment]
Currently the communities with stories (eg. Bavaroe) can not be clicked on. These ones should be diferentiated (issue #36) and clickable and then opens the sidebar for that community. 

Our partners have asked that at the moment only the communities with stories be clickable and appear in the sidebar until they have added more information in about the others.
