### ISSUE TITLE
use stars for stories

### ISSUE THREAD

**Issue by okdistribute** [digidem/alianza-ceibo-maps#36]
the stories are still using the old icon (house with a plus) rather than the star which is in the design

**Comment by ChrisC** [comment]
@karissa it looks like this might be the place to add this feature correct? https://github.com/digidem/alianza-ceibo-maps/blob/master/src/index.js#L250-L258

If so, based on the feature collection being passed here, how do we know a community has a story? Is it any with a `Historias` property? Or something else?

Also, are the icons referenced here the ones in the top-level `static` folder? Or are they being hosted elsewhere?

**Comment by ChrisC** [comment]
@gmaclennan any ideas on the above?

**Comment by okdistribute** [comment]
I believe it is any with the `Historias` property. That block of code you mentioned is for noting solar/agua/none
