### ISSUE TITLE
Insert English Legend 

### ISSUE THREAD

**Issue by aliya-ryan** [digidem/alianza-ceibo-maps#38]
The legend is currently in Spanish on the English version of the map (no longer, but only a temporary fix see below)

**Comment by aliya-ryan** [comment]
As a temporary measure I tried to solve this (so our partners could display it on their English language website) by translating each of the items in the legend.js file. So now both the Spanish and the English are the same. I can put the Spanish back if this is fixed in the better way of the map pulling the en rather than es terms. 

As of 11.40am I had committed this change and merged the branches but not all the changes were appearing on the published map - only the title "Map Legend" appeared in English. All the rest still in Spanish.

**Comment by aliya-ryan** [comment]
This is the code at the beginning of the legend.js before I changed it

const translations = {
  'header': {
    es: 'Leyenda del Mapa',
    en: 'Map Legend'
  },
  'agua': {
    es: 'Instalaciones de agua',
    en: 'Water Installations '
  },
  'solar': {
    es: 'Instalaciones de solar',
    en: 'Solar Installations '
  },
  'agua-solar': {
    es: 'Instalaciones de agua y solar',
    en: 'Water and Solar Installations '
  },
  'agua-solar-story': {
    es: 'Instalaciones de agua y solar con historias',
    en: 'Water and Solar Installations with stories'
  },
  'legal-process': {
    es: 'En proceso de reclamacíon legal',
    en: 'In process of legal claim'
  },
  'territory': {
    es: 'territorio',
    en: 'territory'
  }
}

**Comment by aliya-ryan** [comment]
Greg deployed it all again and it worked. No need for further work on this at the moment.

**Comment by okdistribute** [comment]
simple fix on c5c55a666d0b6c91631e3ca9253df8867bd675cd

**Comment by okdistribute** [comment]
so now it should be working on both spanish and english versions
