### ISSUE TITLE
Initial view of map more zoomed in

### ISSUE THREAD

**Issue by aliya-ryan** [digidem/alianza-ceibo-maps#40]
Is it possible to have the view that appears when you first open the map further zoomed in. Perhaps something resembling this image? On our parters page it appears fully zoomed out initially, and they would like the initial view something easy to click on the areas from (https://www.amazonfrontlines.org/maps/). 

<img width="955" alt="screen shot 2017-11-15 at 16 18 30" src="https://user-images.githubusercontent.com/21277147/32847010-b83508ea-ca20-11e7-9fd5-532af177895a.png">

**Comment by ChrisC** [comment]
scratching my head on how to change the initial zoom on the overview map. @karissa it looks like this initial zoom setting is changed somewhere else as the map loads? Any hints on where zoom is calculated would be much appreciated.... https://github.com/digidem/alianza-ceibo-maps/blob/master/src/index.js#L52

**Comment by okdistribute** [comment]
https://github.com/digidem/alianza-ceibo-maps/blob/master/src/index.js#L111

this is where the map changes bounds

you can zoom on the map and look at the url to find the new zoom/bounds

**Comment by ChrisC** [comment]
@karissa thank you!
