### ISSUE TITLE
Spaces missing between words

### ISSUE THREAD

**Issue by aliya-ryan** [digidem/alianza-ceibo-maps#41]
There are spaces missing in the following places:

- In the second half, between each of the **nationality names** and the word **territorio**
eg. Secoyaterritorio

- In the initial sidebar, underneath the listing of each nationality where it talks about the number of installations
eg. 169INSTALLATIONS

**Comment by okdistribute** [comment]
Something is wrong when the build is made because using budo on the development version it looks okay.

**Comment by aliya-ryan** [comment]
I added spaces before the words in the legend.js - now fixed
