### ISSUE TITLE
Colour at top of sidebar change to #2f604a

### ISSUE THREAD

**Issue by aliya-ryan** [digidem/alianza-ceibo-maps#42]
Our partners have changed the main colours used on their site.

Please change the colour that appears at the top of the sidebar, currently a dark-sea-blue to #2f604a a dark green.

**Comment by aliya-ryan** [comment]
Changed in branch "sidebar-colour" please can someone else review and commit. I have never merged anything on this map before - worried it'll go wrong.

**Comment by okdistribute** [comment]
Looks good
